-- CORRECTION : Supprimer la colonne "relation" qui n'existe pas
-- Exécutez ce SQL dans votre dashboard Supabase

-- Option 1: Supprimer la colonne problématique
ALTER TABLE messages DROP COLUMN IF EXISTS relation;

-- Option 2: Recréer la table correctement
DROP TABLE IF EXISTS messages;

CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY() PRIMARY KEY,
  nom VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Activer les permissions
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Supprimer anciennes politiques
DROP POLICY IF EXISTS "Public messages are viewable by everyone" ON messages;
DROP POLICY IF EXISTS "Anyone can insert messages" ON messages;

-- Recréer les politiques correctes
CREATE POLICY "Public messages are viewable by everyone"
ON messages FOR SELECT
USING (true);

CREATE POLICY "Anyone can insert messages"
ON messages FOR INSERT
WITH CHECK (true);

-- Vérifier la structure
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'messages' 
AND table_schema = 'public';
